name: Database Connection Check

on:
  push:
    branches:
      - main

jobs:
  check-database:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: traveler_registration_user
          POSTGRES_PASSWORD: 9xMSsl85lA4mPR7tuNvHKcGbsCKDYDGX
          POSTGRES_DB: traveler_registration
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 4s
          --health-retries 2

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Let database start
        run: sleep 10

      - name: Check existing tables in traveler_registration
        env:
          DB_HOST: dpg-cv38rvbtq21c73bh5vpg-a.oregon-postgres.render.com
          DB_PORT: 5432
          DB_USER: traveler_registration_user
          DB_PASSWORD: 9xMSsl85lA4mPR7tuNvHKcGbsCKDYDGX
          DB_NAME: traveler_registration
          REQUIRED_TABLE: traveler_registration
        run: |
          echo "Checking database connection..."
          
          DB_NAME_CHECK=$(PGPASSWORD=$DB_PASSWORD psql -h $DB_HOST -U $DB_USER -d $DB_NAME -tAc "SELECT current_database();")
          
          if [ -z "$DB_NAME_CHECK" ]; then
            echo "ERROR: Could not connect to the database."
            exit 1
          fi
          
          echo "Connected to database: $DB_NAME_CHECK"
          if [ "$DB_NAME_CHECK" != "$DB_NAME" ]; then
            echo "ERROR: Not using the correct database."
            exit 1
          fi

          echo "Checking if required table exists..."
          TABLE_EXISTS=$(PGPASSWORD=$DB_PASSWORD psql -h $DB_HOST -U $DB_USER -d $DB_NAME -tAc "SELECT to_regclass('$REQUIRED_TABLE');")

          if [ "$TABLE_EXISTS" == "$REQUIRED_TABLE" ]; then
            echo "Table '$REQUIRED_TABLE' exists."
          else
            echo "ERROR: Table '$REQUIRED_TABLE' does not exist."
            exit 1
          fi

      - name: Success
        run: echo "Database and table checks passed!"