name: Database Connection Check

on:
  push:
    branches:
      - main

jobs:
  check-database:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install PostgreSQL Client
        run: sudo apt-get install -y postgresql-client

      - name: Check Database Connection
        env:
          DB_HOST: dpg-cv38rvbtq21c73bh5vpg-a.oregon-postgres.render.com
          DB_PORT: 5432
          DB_NAME: traveler_registration
          DB_USER: traveler_registration_user
          DB_PASSWORD: 9xMSsl85lA4mPR7tuNvHKcGbsCKDYDGX
        run: |
          echo "Checking database connection..."
          PGPASSWORD=$DB_PASSWORD psql -h $DB_HOST -p $DB_PORT -U $DB_USER -d $DB_NAME -c "SELECT 'Connected to the database' AS status;" || exit 1

      - name: Success
        run: echo "Database connection successful!"
